<?php

namespace App\Services;

use App\Exceptions\BusinessRuleException;
use App\Models\Expense;
use App\Models\PaymentMethod;
use App\Models\RecurringExpense;
use App\Models\UtilityBill;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * The expense ledger.
 *
 * Expenses are cancelled, never deleted, and a cancellation reverses whatever
 * the expense took out of the cashbox. Expenses generated by payroll or trainer
 * payouts are marked system-generated and may only be touched through the
 * module that created them.
 */
class ExpenseService
{
    public function __construct(
        protected CashboxService $cashbox,
        protected NumberGenerator $numbers,
        protected AuditLogger $audit,
    ) {
    }

    /**
     * @param  array{
     *     expense_category_id:int, payment_method_id:int, title:string, amount:float,
     *     spent_on:string, beneficiary?:string|null, invoice_number?:string|null, notes?:string|null
     * }  $data
     */
    public function record(array $data, int $branchId, ?Model $source = null): Expense
    {
        return DB::transaction(function () use ($data, $branchId, $source) {
            $amount = round((float) $data['amount'], 2);

            if ($amount <= 0) {
                throw BusinessRuleException::make(
                    'قيمة المصروف يجب أن تكون أكبر من صفر.',
                    ['amount' => ['قيمة المصروف يجب أن تكون أكبر من صفر.']],
                );
            }

            $method = PaymentMethod::findOrFail($data['payment_method_id']);

            $expense = Expense::create([
                'branch_id' => $branchId,
                'reference' => $this->numbers->expenseReference(),
                'expense_category_id' => $data['expense_category_id'],
                'payment_method_id' => $method->id,
                'title' => $data['title'],
                'amount' => $amount,
                'spent_on' => $data['spent_on'],
                'beneficiary' => $data['beneficiary'] ?? null,
                'invoice_number' => $data['invoice_number'] ?? null,
                'notes' => $data['notes'] ?? null,
                'sourceable_type' => $source ? $source::class : null,
                'sourceable_id' => $source?->getKey(),
                'status' => 'recorded',
                'created_by' => auth()->id(),
            ]);

            if ($method->movesCash()) {
                $this->cashbox->withdraw(
                    cashbox: $this->cashbox->forBranch($branchId),
                    amount: $amount,
                    category: $this->cashboxCategoryFor($source),
                    source: $expense,
                    description: $expense->title.' — '.$expense->reference,
                    date: $expense->spent_on,
                );
            }

            $this->audit->logCreate('expense.recorded', $expense, 'تسجيل مصروف');

            return $expense->fresh(['category', 'paymentMethod']);
        });
    }

    /**
     * Amend an expense.
     *
     * A change to the amount or the payment method re-posts the cash movement,
     * so the ledger keeps matching the expense.
     */
    public function update(Expense $expense, array $data, string $reason): Expense
    {
        return DB::transaction(function () use ($expense, $data, $reason) {
            $this->assertEditable($expense);

            $original = $expense->getOriginal();
            $oldAmount = (float) $expense->amount;
            $oldMethod = $expense->paymentMethod;

            $expense->fill([
                'expense_category_id' => $data['expense_category_id'] ?? $expense->expense_category_id,
                'payment_method_id' => $data['payment_method_id'] ?? $expense->payment_method_id,
                'title' => $data['title'] ?? $expense->title,
                'amount' => isset($data['amount']) ? round((float) $data['amount'], 2) : $expense->amount,
                'spent_on' => $data['spent_on'] ?? $expense->spent_on,
                'beneficiary' => $data['beneficiary'] ?? $expense->beneficiary,
                'invoice_number' => $data['invoice_number'] ?? $expense->invoice_number,
                'notes' => $data['notes'] ?? $expense->notes,
            ]);

            $newMethod = PaymentMethod::find($expense->payment_method_id);
            $cashChanged = (float) $expense->amount !== $oldAmount
                || $oldMethod?->movesCash() !== $newMethod?->movesCash();

            $expense->save();

            if ($cashChanged) {
                $this->cashbox->reverseFor($expense, "تعديل مصروف {$expense->reference}");

                if ($newMethod?->movesCash()) {
                    $this->cashbox->withdraw(
                        cashbox: $this->cashbox->forBranch($expense->branch_id),
                        amount: (float) $expense->amount,
                        category: 'expense',
                        source: $expense,
                        description: $expense->title.' — '.$expense->reference.' (معدّل)',
                        date: $expense->spent_on,
                    );
                }
            }

            $this->audit->logUpdate('expense.updated', $expense, $original, $reason);

            return $expense->fresh();
        });
    }

    /** Cancel an expense and give the cash back to the box. */
    public function cancel(Expense $expense, string $reason): Expense
    {
        return DB::transaction(function () use ($expense, $reason) {
            if ($expense->isCancelled()) {
                throw BusinessRuleException::make('هذا المصروف ملغى مسبقاً.');
            }

            $this->assertEditable($expense);

            $original = $expense->getOriginal();

            $this->cashbox->reverseFor($expense, "إلغاء مصروف {$expense->reference}: {$reason}");

            $expense->update([
                'status' => 'cancelled',
                'cancel_reason' => $reason,
                'cancelled_by' => auth()->id(),
                'cancelled_at' => now(),
            ]);

            $this->audit->log(
                action: 'expense.cancelled',
                subject: $expense,
                before: ['status' => $original['status'], 'amount' => $original['amount']],
                after: ['status' => 'cancelled'],
                reason: $reason,
            );

            return $expense->fresh();
        });
    }

    /** Turn a recurring template into a real expense for one period. */
    public function fromRecurring(RecurringExpense $template, string $spentOn): Expense
    {
        $expense = $this->record([
            'expense_category_id' => $template->expense_category_id,
            'payment_method_id' => $template->payment_method_id
                ?? PaymentMethod::where('code', 'cash')->value('id'),
            'title' => $template->name,
            'amount' => (float) $template->amount,
            'spent_on' => $spentOn,
            'notes' => 'تم إنشاؤه تلقائياً من مصروف متكرر',
        ], $template->branch_id, $template);

        $template->forceFill(['last_generated_on' => $spentOn])->save();

        return $expense;
    }

    /** Settle a utility bill by booking it into the ledger. */
    public function payUtilityBill(UtilityBill $bill, string $paidOn, int $paymentMethodId): UtilityBill
    {
        return DB::transaction(function () use ($bill, $paidOn, $paymentMethodId) {
            if ($bill->isPaid()) {
                throw BusinessRuleException::make('تم دفع هذه الفاتورة مسبقاً.');
            }

            $category = \App\Models\ExpenseCategory::where('code', $this->utilityCategoryCode($bill->service_type))
                ->orWhere('profit_bucket', 'utilities')
                ->orderByRaw('code = ? DESC', [$this->utilityCategoryCode($bill->service_type)])
                ->firstOrFail();

            $expense = $this->record([
                'expense_category_id' => $category->id,
                'payment_method_id' => $paymentMethodId,
                'title' => 'فاتورة '.$bill->serviceLabel().' — '.$bill->billing_month,
                'amount' => (float) $bill->amount,
                'spent_on' => $paidOn,
                'invoice_number' => $bill->invoice_number,
            ], $bill->branch_id, $bill);

            $bill->update([
                'status' => 'paid',
                'paid_on' => $paidOn,
                'payment_method_id' => $paymentMethodId,
                'expense_id' => $expense->id,
            ]);

            $this->audit->log(
                action: 'utility_bill.paid',
                subject: $bill,
                after: ['amount' => $bill->amount, 'expense_id' => $expense->id],
                description: 'دفع فاتورة خدمات',
            );

            return $bill->fresh('expense');
        });
    }

    protected function assertEditable(Expense $expense): void
    {
        if ($expense->isSystemGenerated()) {
            throw BusinessRuleException::make(
                'هذا المصروف تم إنشاؤه تلقائياً من عملية أخرى، ويجب تعديله من مصدره.',
            );
        }
    }

    protected function cashboxCategoryFor(?Model $source): string
    {
        return match (true) {
            $source instanceof \App\Models\PayrollPayment => 'payroll',
            $source instanceof \App\Models\TrainerCompensationPayment => 'trainer_compensation',
            default => 'expense',
        };
    }

    protected function utilityCategoryCode(string $serviceType): string
    {
        return match ($serviceType) {
            'electricity' => 'electricity',
            'water' => 'water',
            'internet' => 'internet',
            'telephone' => 'telephone',
            'rent' => 'rent',
            default => 'other',
        };
    }
}
