<?php

namespace App\Policies;

use App\Models\Expense;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;

/**
 * Expenses are cancelled rather than deleted, and an expense generated by
 * payroll or a trainer payout may only be changed from the module that
 * created it.
 */
class ExpensePolicy extends BasePolicy
{
    protected string $prefix = 'expenses';

    public function update(User $user, Model $model): bool
    {
        return $user->hasPermission('expenses.update')
            && $this->sameBranch($user, $model)
            && ! $model->isCancelled()
            && ! $model->isSystemGenerated();
    }

    public function cancel(User $user, Expense $expense): bool
    {
        return $user->hasPermission('expenses.delete')
            && $this->sameBranch($user, $expense)
            && ! $expense->isCancelled()
            && ! $expense->isSystemGenerated();
    }

    public function delete(User $user, Model $model): bool
    {
        return false;
    }
}
