<?php

namespace App\Models;

use App\Models\Concerns\BelongsToBranch;
use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * A recorded outgoing. Like payments, expenses are cancelled rather than
 * deleted so the ledger and the P&L stay reconstructable.
 */
class Expense extends Model
{
    use BelongsToBranch;
    use HasFactory;
    use HasUuid;
    use SoftDeletes;

    protected $fillable = [
        'branch_id', 'reference', 'expense_category_id', 'payment_method_id', 'title',
        'amount', 'spent_on', 'beneficiary', 'invoice_number', 'notes',
        'sourceable_type', 'sourceable_id', 'status', 'cancel_reason',
        'cancelled_by', 'cancelled_at', 'created_by',
    ];

    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'spent_on' => 'date',
            'cancelled_at' => 'datetime',
        ];
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(ExpenseCategory::class, 'expense_category_id');
    }

    public function paymentMethod(): BelongsTo
    {
        return $this->belongsTo(PaymentMethod::class);
    }

    /** Whatever generated this expense — a payroll payment, payout, bill… */
    public function sourceable(): MorphTo
    {
        return $this->morphTo();
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function canceller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'cancelled_by');
    }

    public function cashboxTransactions(): MorphMany
    {
        return $this->morphMany(CashboxTransaction::class, 'sourceable');
    }

    public function documents(): MorphMany
    {
        return $this->morphMany(Document::class, 'documentable');
    }

    /** Only recorded expenses count against profit. */
    public function scopeRecorded(Builder $query): Builder
    {
        // Qualified: this scope is used alongside joins in the reports.
        return $query->where('expenses.status', 'recorded');
    }

    public function isCancelled(): bool
    {
        return $this->status === 'cancelled';
    }

    /** Expenses generated by payroll or payouts must not be edited by hand. */
    public function isSystemGenerated(): bool
    {
        return $this->sourceable_type !== null;
    }
}
